### ISSUE TITLE
Functional Script

### ISSUE THREAD

**Issue by Jesschop** [dnasko/baby_virome#2]
With the new uniref update the function_assignment.pl per_query output doesnt work. Looks like this: 

NODE_1_length_65404_cov_16.5831_646_1_1 17.6945438216094        
NODE_1_length_65404_cov_16.5831_646_1_1 17.6945438216094        
NODE_1_length_65404_cov_16.5831_646_1_1 17.6945438216094        
NODE_1_length_65404_cov_16.5831_646_1_1 17.6945438216094        
NODE_1_length_65404_cov_16.5831_646_1_1 17.6945438216094        
NODE_1_length_65404_cov_16.5831_1484_660_2      16.8737841024269        
NODE_1_length_65404_cov_16.5831_1951_1496_3     22.854549511651 
NODE_1_length_65404_cov_16.5831_1951_1496_3     22.854549511651 
NODE_1_length_65404_cov_16.5831_1951_1496_3     22.854549511651 
NODE_1_length_65404_cov_16.5831_2888_1944_4     19.1865853712293        
NODE_1_length_65404_cov_16.5831_2888_1944_4     19.1865853712293        
NODE_1_length_65404_cov_16.5831_2888_1944_4     19.1865853712293        
NODE_1_length_65404_cov_16.5831_2888_1944_4     19.1865853712293        
NODE_1_length_65404_cov_16.5831_2888_1944_4     19.1865853712293        
NODE_1_length_65404_cov_16.5831_3333_2899_5     16.543755169369 GO:0030430

**Comment by dnasko** [comment]
This should be fixed I you use the new `functional_assignment_go.pl` script. Note that the way GO terms are assigned and the way SEED functions are assigned are different.

Check to see if this is working and I'll close the ticket.

**Comment by Jesschop** [comment]
Looks good
